### PR TITLE
Bump services and update identifier port mapping

### PR DESCRIPTION
**Pull request by Riadabd**
This PR adjusts some parts of the `docker-compose.dev.yml` file:
* Bump `mock-login` service to `v0.4.0`
* Adjust `identifier` port mapping
* Add `.env.example` similar to what `app-organization-portal` does
* Bump `virtuoso` to `v1.2.0-rc.1`
    - `app-lpdc-digitaal-loket` has been running this version for 3 months without any issues. It has undergone testing by us in addition to the new Kunlabora team that has taken over the project. We have also gone to production with this virtuoso version, and so far, all looks good.

### CODE REVIEW

**Comment by aatauil** [comment]
I dont immediatly get the env.example file. What is it needed for? Also, in comparison to OP, there is the additional "docker-compose.override.yml" inside the COMPOSE variable.

**Comment by Riadabd** [comment]
The `.env.example` makes it quicker to run the stack as you just have to `cp .env.example .env` and then up the stack. Time-wise, the difference between creating the file from scratch and adding the docker compose files manually may be insignificant, but I found it nicer to have it directly on the repo.

For `docker-compose.override.yml` in the COMPOSE variable, I'll remove it since it will cause issues in case no override file is present.

**Comment by Riadabd** [comment]
Should we also bump identifier to `v1.10.1`? It has a fix for when `mu-auth` is exposed directly, which isn't done in the app at the moment I think. But given the app is not deployed on production yet, I feel it's better to have it there for future-proofing.

**Comment by aatauil** [comment]
> Should we also bump identifier to `v1.10.1`? It has a fix for when `mu-auth` is exposed directly, which isn't done in the app at the moment I think. But given the app is not deployed on production yet, I feel it's better to have it there for future-proofing.

I agree. Could you bump it ? I'll make sure to test it

**Review by aatauil — APPROVED** [review]
Everything still seems to work, though the virtuoso.trx file that hold transaction logs needed to be deleted since it isnt compatible across versions

**Pull request merged**
